# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrEDD-f6vV4tzn90h3-1NTIoq9OyKB8G
"""

from typing_extensions import get_protocol_members
X = str(input("colour"))
if X == "green":
   print("go")
elif X == "yellow":
    print("wait")
else:
    print(" stop")

x = int(input("enter the nuber"))
i=1
for i in range( i, x+ 1, 2):
  print(i)

x = int(input("age"))
if x>= 18 :
  print ("elligibe for vote")
else:
  print ("not elliglbe for vote")

x = int(input(" positive or negative"))
if x <0:
  print("negative")
else :
   print("positive")

x = int(input("enter number"))
if x<10 :
   print ("single digit")
elif x<100:
   print("two digit")
else :
  print (" three digit")

x = int(input("enter number"))
if x %3 ==0 :
   print (" divisible by three")
else :
   print ("not divisible by three")